title: Big Ju's Base
author: Me
email: jhass1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description. an awesome description

# social links
twitter_username: your-twitter-handle
github_username:  BigJU01

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
